### ISSUE TITLE
Need help with project - Capturing the Picture only

### ISSUE THREAD

**Issue by aribamazharam** [Jayanths9/Virtual_Makeup_opencv#1]
Need help...

1) There might be an issue with the project itself, causing it to stop after capturing the picture.

2)I might be missing something on how to run the project properly.

Could you please help me troubleshoot this?

**Comment by Jayanths9** [comment]
Try Running Camera.py to capture video and apply facial transformation

**Comment by Jayanths9** [comment]
Try Running Camera.py to capture video and apply facial transformation
